name: Build and Release Electron App
on:
  push:
    branches:
      - main
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    name: Build and Release
    runs-on: windows-latest
    steps:
    - name: setting GH-Token
      uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm install
    - name: installing electronbuilder
      run: npm install electron-builder -g
    - name: Build app
      run: electron-builder --windows --publish always
